version: 2
updates:
  - package-ecosystem: npm
    directory: /datacollector-ui
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /e2e-tests
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
